version: '3.8'

services:
  db:
    image: postgres:15
    container_name: product-db
    restart: always
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: product-api
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    command: ["java", "-jar", "target/product-catalog-0.0.1-SNAPSHOT.jar"]

volumes:
  pg_data:
